// catalog-service/digilib-user-frontend/src/components/PageHeader.jsx
import React from 'react';
export default function PageHeader({ current, title, description, right }) {
  return (
    <div className="page-head">
      <div>
        <div className="breadcrumb">Trang chủ <span>/</span> {current || title}</div>
        <h1>{title}</h1>
        {description && <p>{description}</p>}
      </div>
      {right}
    </div>
  );
}

// frontend/digilib-admin-frontend/src/components/PageHeader.vue
<template>
  <div class="page-head">
    <div>
      <h1 class="page-title">{{ title }}</h1>
      <p v-if="subtitle" class="page-subtitle">{{ subtitle }}</p>
      <div v-if="breadcrumb" class="breadcrumb">Trang chủ › {{ breadcrumb }}</div>
    </div>
    <slot />
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, required: true },
  subtitle: { type: String, default: '' },
  breadcrumb: { type: String, default: '' }
})
</script>
