// frontend/src/pages/auth/Login.vue
<template>
  <div class="d-flex" style="min-height: 100vh;">
    <!-- Left: Login Form -->
    <div class="flex-grow-1 d-flex flex-column justify-center py-12 px-4 px-sm-6 px-lg-16 px-xl-24" style="max-width: 600px;">
      <div style="max-width: 400px; width: 100%; margin: 0 auto;">
        <div class="d-flex align-center mb-2">
          <v-icon color="primary" size="40" class="mr-3">mdi-book-open-page-variant</v-icon>
          <span class="text-h4 font-weight-black text-grey-darken-4">DigiLib</span>
        </div>
        <h3 class="text-h5 font-weight-bold text-grey-darken-4 mt-6">Đăng nhập hệ thống</h3>
        <p class="text-body-2 text-grey mt-2">Nhập email và mật khẩu để tiếp tục</p>

        <v-alert v-if="error" type="error" variant="tonal" density="compact" class="mt-4" closable @click:close="error = ''">
          {{ error }}
        </v-alert>

        <v-form @submit.prevent="handleLogin" class="mt-8">
          <div class="mb-4">
            <label class="text-body-2 font-weight-medium text-grey-darken-3 mb-1 d-block">Email / Tài khoản</label>
            <v-text-field
              v-model="email"
              placeholder="admin@smartlib.local"
              type="email"
              prepend-inner-icon="mdi-email-outline"
              required
              hide-details
            />
          </div>

          <div class="mb-4">
            <label class="text-body-2 font-weight-medium text-grey-darken-3 mb-1 d-block">Mật khẩu</label>
            <v-text-field
              v-model="password"
              placeholder="••••••••"
              :type="showPass ? 'text' : 'password'"
              prepend-inner-icon="mdi-lock-outline"
              :append-inner-icon="showPass ? 'mdi-eye-off' : 'mdi-eye'"
              @click:append-inner="showPass = !showPass"
              required
              hide-details
            />
          </div>

          <div class="d-flex align-center justify-space-between mb-6">
            <v-checkbox v-model="remember" label="Ghi nhớ đăng nhập" density="compact" hide-details color="primary" />
            <a href="#" class="text-primary text-body-2 font-weight-medium text-decoration-none">Quên mật khẩu?</a>
          </div>

          <v-btn type="submit" color="primary" size="x-large" block :loading="loading">
            Đăng nhập
          </v-btn>

          <p class="text-center text-body-2 text-grey mt-6">
            Chưa có tài khoản?
            <router-link to="/register" class="text-primary font-weight-medium text-decoration-none">Đăng ký ngay</router-link>
          </p>
        </v-form>
      </div>
    </div>

    <!-- Right: Hero Image -->
    <div class="d-none d-lg-block flex-grow-1 position-relative" style="background: #1976D2; min-width: 50%;">
      <img
        src="https://images.unsplash.com/photo-1507842217343-583bb7270b66?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"
        alt="Thư viện"
        style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; opacity: 0.7; mix-blend-mode: multiply;"
      />
      <div style="position: absolute; inset: 0; background: linear-gradient(to top, #1976D2, transparent, transparent); opacity: 0.9;" />
      <div style="position: absolute; bottom: 48px; left: 48px; max-width: 480px;">
        <h1 class="text-h3 font-weight-bold text-white mb-4">Khám phá tri thức vô tận</h1>
        <p class="text-subtitle-1 text-blue-lighten-3">
          Hệ thống quản lý thư viện số hiện đại, giúp bạn dễ dàng tìm kiếm, mượn trả và theo dõi kho tàng kiến thức.
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../stores/authStore'
import { authApi } from '../../services/authApi'

const router = useRouter()
const auth = useAuthStore()

const email = ref('')
const password = ref('')
const remember = ref(false)
const showPass = ref(false)
const loading = ref(false)
const error = ref('')

async function handleLogin() {
  loading.value = true
  error.value = ''
  try {
    const { data } = await authApi.login(email.value, password.value)
    auth.setAuth(data.accessToken || data.token, data.user)
    router.push({ name: 'Dashboard' })
  } catch (e) {
    error.value = e.response?.data?.message || 'Đăng nhập thất bại. Vui lòng kiểm tra lại.'
  } finally {
    loading.value = false
  }
}
</script>

// design/src/app/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router';
import { useAuth, Role } from '../context/AuthContext';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Label } from '../components/ui/Label';
import { BookOpen } from 'lucide-react';
import { ImageWithFallback } from '../components/figma/ImageWithFallback';

export function Login() {
  const [role, setRole] = useState<Role>('ADMIN');
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    login(role);
    if (role === 'ADMIN') navigate('/admin');
    if (role === 'LIBRARIAN') navigate('/librarian');
    if (role === 'READER') navigate('/reader');
  };

  return (
    <div className="min-h-screen flex bg-gray-50 font-sans">
      <div className="flex-1 flex flex-col justify-center py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24">
        <div className="mx-auto w-full max-w-sm lg:w-96">
          <div className="flex items-center gap-3">
            <BookOpen className="w-10 h-10 text-[#1976D2]" />
            <h2 className="text-3xl font-extrabold text-gray-900">DigiLib</h2>
          </div>
          <h3 className="mt-6 text-2xl font-bold text-gray-900">Đăng nhập hệ thống</h3>
          <p className="mt-2 text-sm text-gray-600">
            Chọn vai trò để tiếp tục (Bản Demo Frontend)
          </p>

          <div className="mt-8">
            <form onSubmit={handleLogin} className="space-y-6">
              <div>
                <Label htmlFor="role">Vai trò</Label>
                <div className="mt-1">
                  <select
                    id="role"
                    name="role"
                    className="block w-full h-10 rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-[#1976D2] focus:outline-none focus:ring-1 focus:ring-[#1976D2]"
                    value={role || ''}
                    onChange={(e) => setRole(e.target.value as Role)}
                  >
                    <option value="ADMIN">Quản trị viên (Admin)</option>
                    <option value="LIBRARIAN">Thủ thư (Librarian)</option>
                    <option value="READER">Độc giả (Reader)</option>
                  </select>
                </div>
              </div>

              <div>
                <Label htmlFor="email">Email / Tài khoản</Label>
                <div className="mt-1">
                  <Input id="email" type="text" placeholder="admin@digilib.com" required />
                </div>
              </div>

              <div>
                <Label htmlFor="password">Mật khẩu</Label>
                <div className="mt-1">
                  <Input id="password" type="password" placeholder="••••••••" required />
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  <input
                    id="remember-me"
                    name="remember-me"
                    type="checkbox"
                    className="h-4 w-4 rounded border-gray-300 text-[#1976D2] focus:ring-[#1976D2]"
                  />
                  <label htmlFor="remember-me" className="ml-2 block text-sm text-gray-900">
                    Ghi nhớ đăng nhập
                  </label>
                </div>

                <div className="text-sm">
                  <a href="#" className="font-medium text-[#1976D2] hover:text-[#1565C0]">
                    Quên mật khẩu?
                  </a>
                </div>
              </div>

              <div>
                <Button type="submit" className="w-full h-12 text-lg">
                  Đăng nhập
                </Button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div className="hidden lg:block relative w-0 flex-1 bg-[#1976D2]">
        <img
          className="absolute inset-0 h-full w-full object-cover opacity-80 mix-blend-multiply"
          src="https://images.unsplash.com/photo-1507842217343-583bb7270b66?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"
          alt="Thư viện"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-[#1976D2] via-transparent to-transparent opacity-90" />
        <div className="absolute bottom-12 left-12 text-white max-w-xl">
          <h1 className="text-4xl font-bold mb-4">Khám phá tri thức vô tận</h1>
          <p className="text-lg text-blue-100">
            Hệ thống quản lý thư viện số hiện đại, giúp bạn dễ dàng tìm kiếm, mượn trả và theo dõi kho tàng kiến thức.
          </p>
        </div>
      </div>
    </div>
  );
}
